name: Build and deploy

# Only trigger, when the test workflow succeeded
on:
  workflow_run:
    workflows: ["Test and Lint"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Step 5 - Build
        run: yarn run build

  deploy-chromatic:
    name: Deploy to chromatic
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          # our project token, to see how to obtain it
          # refer to https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    needs: build
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          git config --global user.email "kamionorato@gmail.com"
          git config --global user.name "LadyKamille"
          yarn run deploy
