name: Deploy github pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out Git repository
        uses: actions/checkout@v2

      - name: Step 2- Build
        run: yarn run build

      - name: Step 3 - Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
