name: Build, test, and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # ESLint and Prettier must be in `package.json`
      - name: Install modules
        run: yarn

  lint:
    needs: setup
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: yarn run eslint .

  test:
    needs: setup
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: yarn run tests

  build:
    needs:
      - test
      - lint
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: yarn run build

  deploy-chromatic:
    needs:
      - test
      - lint
    name: Deploy Chromatic
    runs-on: ubuntu-latest

    steps:
      - name: Build Chromatic
        uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          # our project token, to see how to obtain it
          # refer to https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          git config --global user.email "kamionorato@gmail.com"
          git config --global user.name "LadyKamille"
          yarn run deploy
