name: Build

on: push

jobs:
  run-linters:
    name: Run linter and tests
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Check out Git repository
        uses: actions/checkout@v1

      # ESLint and Prettier must be in `package.json`
      - name: Step 2 - Install modules
        run: yarn

      - name: Step 3 - Run linters
        run: yarn run eslint . --fix

      - name: Step 4 - Build Chromatic
        uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          # our project token, to see how to obtain it
          # refer to https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
