name: Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Checkout repo and install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      # ESLint and Prettier must be in `package.json`
      - name: Install modules
        run: yarn
