name: Test and Lint

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Setup"]
    types:
      - completed

jobs:
  lint:
    needs: setup
    name: Run eslint and tests
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: yarn run eslint .

  test:
    needs: setup
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: yarn run tests
